version: '3'
services:
  okane-db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: okane
      MARIADB_USER: okane
      MARIADB_PASSWORD: okane
      TZ: "Asia/Tokyo"
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - okane-rdb-volume:/var/lib/mysql
volumes:
  okane-rdb-volume:
networks:
  default:
    driver: bridge